### ISSUE TITLE
Upgrade required: Refresh token is not valid

### ISSUE THREAD

**Issue by 5E7EN** [wictorwilen/ring-timelapse#15]
### Problem

After generating a refresh token using the recommended method and setting the TOKEN variable, I've been encountering an error upon attempting to take snapshots:

```
Error: Refresh token is not valid.  Unable to authenticate with Ring servers.  See https://github.com/dgreif/ring/wiki/Refresh-Tokens
    at RingRestClient.<anonymous> (REDACTED\node_modules\ring-client-api\lib\api\rest-client.js:113:36)
    at Generator.next (<anonymous>)
    at REDACTED\node_modules\ring-client-api\lib\api\rest-client.js:8:71
    at new Promise (<anonymous>)
    at RingRestClient.getAuth (REDACTED\node_modules\ring-client-api\lib\api\rest-client.js:112:16)
    at RingRestClient.<anonymous> (REDACTED\node_modules\ring-client-api\lib\api\rest-client.js:137:33)
    at Generator.throw (<anonymous>)
    at rejected (REDACTED\node_modules\ring-client-api\lib\api\rest-client.js:6:65)
```

### Solution
The `ring-client-api` npm package dependency needs to be upgraded. 
I've tested by using version `11.8.1` which resolves the error.

**Comment by wictorwilen** [comment]
Packages is updated. Please use version 2 of ring-timelapse. Let me know if it works.
